/**
 * Copyright (c) 2007-2015, Institute of Information Systems (Sven Groppe and contributors of LUPOSDATE), University of Luebeck
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 	- Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * 	  disclaimer.
 * 	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * 	  following disclaimer in the documentation and/or other materials provided with the distribution.
 * 	- Neither the name of the University of Luebeck nor the names of its contributors may be used to endorse or promote
 * 	  products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* Generated By:JavaCC: Do not edit this line. SPARQL1_1ParserVisitor.java Version 5.0 */
package lupos.sparql1_1.operatorgraph;

import lupos.datastructures.items.Item;
import lupos.datastructures.items.Variable;
import lupos.engine.operators.BasicOperator;
import lupos.sparql1_1.*;
import lupos.sparql1_1.operatorgraph.helper.OperatorConnection;
public interface SPARQL1_1OperatorgraphGeneratorVisitor
{
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTGroupConstraint} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(ASTGroupConstraint node, OperatorConnection connection, Item graphConstraint);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTQuery} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTQuery node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTSelectQuery} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(ASTSelectQuery node, OperatorConnection connection, Item graphConstraint);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTSelectQuery} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTSelectQuery node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTConstructQuery} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTConstructQuery node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTAskQuery} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTAskQuery node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTOrderConditions} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTOrderConditions node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTLimit} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTLimit node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTOffset} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTOffset node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTLoad} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTLoad node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTClear} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTClear node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTDrop} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTDrop node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTCreate} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTCreate node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTInsert} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTInsert node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTDelete} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTDelete node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTModify} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTModify node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTGraphConstraint} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTGraphConstraint node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTOptionalConstraint} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(ASTOptionalConstraint node, OperatorConnection connection, Item graphConstraint);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTService} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTService node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTMinus} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(ASTMinus node, OperatorConnection connection, Item graphConstraint);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTUnionConstraint} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(ASTUnionConstraint node, OperatorConnection connection, Item graphConstraint);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTFilterConstraint} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(ASTFilterConstraint node, OperatorConnection connection, Item graphConstraint);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTArbitraryOccurences} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTArbitraryOccurences node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTOptionalOccurence} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTOptionalOccurence node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTArbitraryOccurencesNotZero} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTArbitraryOccurencesNotZero node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTPathSequence} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTPathSequence node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTPathAlternative} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTPathAlternative node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTNegatedPath} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTNegatedPath node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTInvers} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTInvers node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTQuotedURIRef} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   * @param subject a {@link lupos.datastructures.items.Variable} object.
   * @param object a {@link lupos.datastructures.items.Variable} object.
   * @param subjectNode a lupos$sparql1_1$Node object.
   * @param objectNode a lupos$sparql1_1$Node object.
   * @return a {@link lupos.engine.operators.BasicOperator} object.
   */
  public BasicOperator visit(ASTQuotedURIRef node, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTDefaultGraph} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTDefaultGraph node, OperatorConnection connection);
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTNamedGraph} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   */
  public void visit(ASTNamedGraph node, OperatorConnection connection);
  // for stream-based evaluation:
  /**
   * <p>visit.</p>
   *
   * @param node a {@link lupos.sparql1_1.ASTWindow} object.
   * @param connection a {@link lupos.sparql1_1.operatorgraph.helper.OperatorConnection} object.
   * @param graphConstraint a {@link lupos.datastructures.items.Item} object.
   */
  public void visit(final ASTWindow node, OperatorConnection connection, Item graphConstraint);
}
