/* Generated By:JJTree: Do not edit this line. ASTDoubleCircumflex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.csv;

public
class ASTDoubleCircumflex extends SimpleNode {
  public ASTDoubleCircumflex(int id) {
    super(id);
  }

  public ASTDoubleCircumflex(CSVParser p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=8c4b67dcb3f1f89d017ddbdfe53e21cb (do not edit this line) */
