/* Generated By:JJTree: Do not edit this line. ASTEmptyNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.csv;

public
class ASTEmptyNode extends SimpleNode {
  public ASTEmptyNode(int id) {
    super(id);
  }

  public ASTEmptyNode(CSVParser p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=e8ec63b4f5e08de9b2521d631791f177 (do not edit this line) */
