/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.csv;

import java.math.BigInteger;

public class ASTInteger extends SimpleNode {

	private BigInteger value;

	public ASTInteger(int id) {
		super(id);
	}

	public ASTInteger(CSVParser p, int id) {
		super(p, id);
	}

	public BigInteger getValue() {
		return value;
	}

	public void setValue(final BigInteger value) {
		this.value = value;
	}

	public void setValue(final int value) {
		this.value = new BigInteger("" + value);
	}

	public void setStringInt(String value) {
		while(value.startsWith("+"))
			value=value.substring(1);
		this.value = new BigInteger(value);
	}

	@Override
	public String toString() {
		return super.toString() + "  " + value;
	}
}
/* JavaCC - OriginalChecksum=567b8cd7fff0dacfc31a23f6b04a99f3 (do not edit this line) */
