/* Generated By:JJTree: Do not edit this line. ASTQuotedURIRef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.csv;

public class ASTQuotedURIRef extends SimpleNode {

	private String qRef;

	public ASTQuotedURIRef(int id) {
		super(id);
	}

	public ASTQuotedURIRef(CSVParser p, int id) {
		super(p, id);
	}

	public String getQRef() {
		return qRef;
	}

	public void setQRef(String qRef) {
		this.qRef = qRef;
	}

	public String toQueryString() {
		return "<" + this.qRef + ">";
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return qRef;
	}
}
/* JavaCC - OriginalChecksum=580cbe96d458886859ca50ad019b6c4c (do not edit this line) */
