/* Generated By:JJTree: Do not edit this line. ASTResult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.csv;

public
class ASTResult extends SimpleNode {
  public ASTResult(int id) {
    super(id);
  }

  public ASTResult(CSVParser p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=260b478d57f22efebf0bd7102e98645d (do not edit this line) */
