/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.csv;

public
class ASTVar extends SimpleNode {
	
  private String name;
	
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(CSVParser p, int id) {
    super(p, id);
  }

  public String getName() {
	  return name;
  }

  public void setName(String name) {
	  this.name = name;
  }

  public String toQueryString(){
	  return "?"+getName();
  }

  @Override
  public String toString() {
	  return super.toString()+" "+name;
  }
}
/* JavaCC - OriginalChecksum=c7e19308bcab0f760aeb88df77eb04b0 (do not edit this line) */
