/**
 * Copyright (c) 2012, Institute of Information Systems (Sven Groppe), University of Luebeck
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 	- Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * 	  disclaimer.
 * 	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * 	  following disclaimer in the documentation and/or other materials provided with the distribution.
 * 	- Neither the name of the University of Luebeck nor the names of its contributors may be used to endorse or promote
 * 	  products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* Generated By:JavaCC: Do not edit this line. CSVParserTreeConstants.java Version 5.0 */
package lupos.endpoint.client.formatreader.csv;

public interface CSVParserTreeConstants
{
  public int JJTRESULT = 0;
  public int JJTVARS = 1;
  public int JJTONERESULT = 2;
  public int JJTVAR = 3;
  public int JJTVALUE = 4;
  public int JJTNIL = 5;
  public int JJTRDFLITERAL = 6;
  public int JJTDOUBLECIRCUMFLEX = 7;
  public int JJTLANGTAG = 8;
  public int JJTVOID = 9;
  public int JJTINTEGER = 10;
  public int JJTFLOATINGPOINT = 11;
  public int JJTBOOLEANLITERAL = 12;
  public int JJTSTRINGLITERAL = 13;
  public int JJTQUOTEDURIREF = 14;
  public int JJTBLANKNODE = 15;
  public int JJTEMPTYNODE = 16;


  public String[] jjtNodeName = {
    "Result",
    "Vars",
    "OneResult",
    "Var",
    "Value",
    "NIL",
    "RDFLiteral",
    "DoubleCircumflex",
    "LangTag",
    "void",
    "Integer",
    "FloatingPoint",
    "BooleanLiteral",
    "StringLiteral",
    "QuotedURIRef",
    "BlankNode",
    "EmptyNode",
  };
}
/* JavaCC - OriginalChecksum=1a9c6ecf5007abb979d053d1138df49b (do not edit this line) */
