/* Generated By:JJTree&JavaCC: Do not edit this line. CSVParserConstants.java */
package lupos.endpoint.client.formatreader.csv;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSVParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IRI_REF = 4;
  /** RegularExpression Id. */
  int PNAME_NS = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int PNAME_LN = 8;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 9;
  /** RegularExpression Id. */
  int LANGTAG = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int DECIMAL = 12;
  /** RegularExpression Id. */
  int DOUBLE = 13;
  /** RegularExpression Id. */
  int EXPONENT = 14;
  /** RegularExpression Id. */
  int STRING_LITERAL = 15;
  /** RegularExpression Id. */
  int NIL = 16;
  /** RegularExpression Id. */
  int WS = 17;
  /** RegularExpression Id. */
  int ANON = 18;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 19;
  /** RegularExpression Id. */
  int PN_CHARS_U = 20;
  /** RegularExpression Id. */
  int PN_CHARS = 21;
  /** RegularExpression Id. */
  int PN_PREFIX = 22;
  /** RegularExpression Id. */
  int PN_LOCAL = 23;
  /** RegularExpression Id. */
  int PLX = 24;
  /** RegularExpression Id. */
  int PERCENT = 25;
  /** RegularExpression Id. */
  int HEX = 26;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "<token of kind 3>",
    "<IRI_REF>",
    "<PNAME_NS>",
    "\"true\"",
    "\"false\"",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<LANGTAG>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<NIL>",
    "<WS>",
    "<ANON>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<PLX>",
    "<PERCENT>",
    "<HEX>",
    "<PN_LOCAL_ESC>",
    "\"\\n\"",
    "\",\"",
    "\"^^\"",
  };

}
