
/**
 * Copyright (c) 2007-2015, Institute of Information Systems (Sven Groppe and contributors of LUPOSDATE), University of Luebeck
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 	- Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * 	  disclaimer.
 * 	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * 	  following disclaimer in the documentation and/or other materials provided with the distribution.
 * 	- Neither the name of the University of Luebeck nor the names of its contributors may be used to endorse or promote
 * 	  products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author groppe
 * @version $Id: $Id
 */
/* Generated By:JJTree&JavaCC: Do not edit this line. CSVParser.java */
package lupos.endpoint.client.formatreader.csv;

import java.io.InputStream;
import java.io.StringReader;
import java.net.URISyntaxException;

import lupos.datastructures.items.literal.LanguageTaggedLiteralOriginalLanguage;
import lupos.datastructures.items.literal.Literal;
import lupos.datastructures.items.literal.LiteralFactory;
import lupos.datastructures.items.literal.TypedLiteralOriginalContent;
import lupos.datastructures.items.literal.URILiteral;
public class CSVParser/*@bgen(jjtree)*/implements CSVParserTreeConstants, CSVParserConstants {/*@bgen(jjtree)*/
  /**
   * <p>main.</p>
   *
   */
  protected JJTCSVParserState jjtree = new JJTCSVParserState();public static void main(final String args [])
  {
    System.out.println("enter query...");
    final CSVParser parser = new CSVParser(System.in);

    try
    {
        parser.expr();
        System.out.println("Result:");
                        ((SimpleNode) parser.jjtree.rootNode()).dump("|");
        } catch(final Exception e) {
                System.out.println(e);
                e.printStackTrace();
        }
  }

        /**
         * <p>getLiteral.</p>
         *
         * @param n a {@link lupos.endpoint.client.formatreader.csv.Node} object.
         * @return a {@link lupos.datastructures.items.literal.Literal} object.
         */
        public static Literal getLiteral(final Node n) {
          return getLiteral(n, false);
        }

        /**
         * <p>getLiteral.</p>
         *
         * @param n a {@link lupos.endpoint.client.formatreader.csv.Node} object.
         * @param allowLazyLiteral a boolean.
         * @return a {@link lupos.datastructures.items.literal.Literal} object.
         */
        public static Literal getLiteral(Node n, final boolean allowLazyLiteral) {
                Literal literal = null;

                if (n instanceof ASTNIL) {
                        try {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createURILiteral("<http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>")
                                                : LiteralFactory
                                                                .createURILiteralWithoutLazyLiteral("<http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>");
                        } catch (final URISyntaxException e1) {
                                e1.printStackTrace();
                        }
                } else if (n instanceof ASTBlankNode) {
                        final ASTBlankNode blankNode = (ASTBlankNode) n;
                        final String name = blankNode.getIdentifier();
                        literal = (allowLazyLiteral) ? LiteralFactory
                                        .createAnonymousLiteral(name) : LiteralFactory
                                        .createAnonymousLiteralWithoutLazyLiteral(name);
                } else if (n instanceof ASTQuotedURIRef) {
                        final ASTQuotedURIRef uri = (ASTQuotedURIRef) n;
                        final String name = uri.getQRef();

                        if (URILiteral.isURI("<" + name + ">")) {
                                try {
                                        literal = (allowLazyLiteral) ? LiteralFactory
                                                        .createURILiteral("<" + name + ">")
                                                        : LiteralFactory
                                                                        .createURILiteralWithoutLazyLiteral("<"
                                                                                        + name + ">");
                                } catch (final Exception e) {
                                        literal = (allowLazyLiteral) ? LiteralFactory
                                                        .createLiteral("<" + name + ">") : LiteralFactory
                                                        .createLiteralWithoutLazyLiteral("<" + name + ">");
                                }
                        } else {
							literal = (allowLazyLiteral) ? LiteralFactory.createLiteral("<"
							                + name + ">") : LiteralFactory
							                .createLiteralWithoutLazyLiteral("<" + name + ">");
						}
                } else if (n instanceof ASTRDFLiteral) {
					n = n.jjtGetChild(0);
				}

                if (literal != null) {
					return literal;
				}

                if (n instanceof ASTStringLiteral) {
                        final ASTStringLiteral lit = (ASTStringLiteral) n;
                        final String quotedContent = lit.getStringLiteral();

                        try {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createTypedLiteral(quotedContent,
                                                                "<http://www.w3.org/2001/XMLSchema#string>")
                                                : TypedLiteralOriginalContent.createTypedLiteral(
                                                                quotedContent,
                                                                "<http://www.w3.org/2001/XMLSchema#string>");
                        } catch (final URISyntaxException e) {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createLiteral(quotedContent) : LiteralFactory
                                                .createLiteralWithoutLazyLiteral(quotedContent);
                        }
                } else if (n instanceof ASTInteger) {
                        final ASTInteger lit = (ASTInteger) n;
                        final String content = String.valueOf(lit.getValue());

                        try {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createTypedLiteral("\u005c"" + content + "\u005c"",
                                                                "<http://www.w3.org/2001/XMLSchema#integer>")
                                                : TypedLiteralOriginalContent.createTypedLiteral("\u005c""
                                                                + content + "\u005c"",
                                                                "<http://www.w3.org/2001/XMLSchema#integer>");
                        } catch (final URISyntaxException e) {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createLiteral(content) : LiteralFactory
                                                .createLiteralWithoutLazyLiteral(content);
                        }
                } else if (n instanceof ASTFloatingPoint) {
                        final ASTFloatingPoint lit = (ASTFloatingPoint) n;
                        final String content = lit.getValue();

                        try {
                                if (content.contains("e") || content.contains("E")) {
									literal = (allowLazyLiteral) ? LiteralFactory
									                .createTypedLiteral("\u005c"" + content + "\u005c"",
									                                "<http://www.w3.org/2001/XMLSchema#double>")
									                : TypedLiteralOriginalContent
									                                .createTypedLiteral("\u005c"" + content + "\u005c"",
									                                                "<http://www.w3.org/2001/XMLSchema#double>");
								} else {
									literal = (allowLazyLiteral) ? LiteralFactory
									                .createTypedLiteral("\u005c"" + content + "\u005c"",
									                                "<http://www.w3.org/2001/XMLSchema#decimal>")
									                : TypedLiteralOriginalContent
									                                .createTypedLiteral("\u005c"" + content + "\u005c"",
									                                                "<http://www.w3.org/2001/XMLSchema#decimal>");
								}
                        } catch (final URISyntaxException e) {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createLiteral(content) : LiteralFactory
                                                .createLiteralWithoutLazyLiteral(content);
                        }
                } else if (n instanceof ASTBooleanLiteral) {
                        final String content = ((ASTBooleanLiteral) n).getState() + "";

                        try {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createTypedLiteral("\u005c"" + content + "\u005c"",
                                                                "<http://www.w3.org/2001/XMLSchema#boolean>")
                                                : TypedLiteralOriginalContent.createTypedLiteral("\u005c""
                                                                + content + "\u005c"",
                                                                "<http://www.w3.org/2001/XMLSchema#boolean>");
                        } catch (final URISyntaxException e) {
                                literal = (allowLazyLiteral) ? LiteralFactory
                                                .createLiteral(content) : LiteralFactory
                                                .createLiteralWithoutLazyLiteral(content);
                        }
                } else if (n instanceof ASTDoubleCircumflex) {
                        if (n.jjtGetNumChildren() != 2) {
							System.err.println(n + " is expected to have 2 children!");
						} else {
                                final String content = getLiteral(n.jjtGetChild(0), allowLazyLiteral).toString();
                                final String type = getLiteral(n.jjtGetChild(1), allowLazyLiteral).toString();

                                try {
                                        literal = (allowLazyLiteral) ? LiteralFactory
                                                        .createTypedLiteral(content, type)
                                                        : TypedLiteralOriginalContent.createTypedLiteral(
                                                                        content, type);
                                } catch (final Exception e) {
                                        literal = (allowLazyLiteral) ? LiteralFactory
                                                        .createLiteral(content + "^^" + type)
                                                        : LiteralFactory
                                                                        .createLiteralWithoutLazyLiteral(content
                                                                                        + "^^" + type);
                                }
                        }
                } else if (n instanceof ASTLangTag) {
                        final String content = getLiteral(n.jjtGetChild(0), allowLazyLiteral).toString();
                        final String lang = ((ASTLangTag) n).getLangTag();
                        literal = (allowLazyLiteral) ? LiteralFactory
                                        .createLanguageTaggedLiteral(content, lang)
                                        : LanguageTaggedLiteralOriginalLanguage
                                                        .createLanguageTaggedLiteral(content, lang);
                } else {
					System.err.println("Unexpected type! "
					                + n.getClass().getSimpleName());
				}

                return literal;
        }

  /**
   * <p>parse.</p>
   *
   * @param query a {@link java.lang.String} object.
   * @return a {@link lupos.endpoint.client.formatreader.csv.SimpleNode} object.
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  public static SimpleNode parse(final String query) throws ParseException {
    final CSVParser parser = new CSVParser(new StringReader(query));
    switch (parser.expr())
    {
      default :
                try {
                        return ((SimpleNode) parser.jjtree.rootNode());
                } catch(final Exception e) {
                        return null;
                }
      case 0 : return null;
      case - 1 : return null;
    }
  }

  /**
   * <p>parse.</p>
   *
   * @param inputStream a {@link java.io.InputStream} object.
   * @return a {@link lupos.endpoint.client.formatreader.csv.SimpleNode} object.
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  public static SimpleNode parse(final InputStream inputStream) throws ParseException {
    final CSVParser parser = new CSVParser(inputStream);
    switch (parser.expr())
    {
      default :
                try {
                        return ((SimpleNode) parser.jjtree.rootNode());
                } catch(final Exception e) {
                        return null;
                }
      case 0 : return null;
      case - 1 : return null;
    }
  }

  /**
   * <p>expr.</p>
   *
   * @return a int.
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public int expr() throws ParseException {
 /*@bgen(jjtree) Result */
  final ASTResult jjtn000 = new ASTResult(JJTRESULT);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      this.firstLine();
      this.jj_consume_token(28);
      label_1:
      while (true) {
        switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
        case IRI_REF:
        case TRUE:
        case FALSE:
        case BLANK_NODE_LABEL:
        case INTEGER:
        case DECIMAL:
        case DOUBLE:
        case STRING_LITERAL:
        case NIL:
        case ANON:
        case 28:
        case 29:
          ;
          break;
        default:
          this.jj_la1[0] = this.jj_gen;
          break label_1;
        }
        this.resultLine();
      }
      this.jj_consume_token(0);
      this.jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      {if (true) {
		return 1;
	}}
    } catch (final Throwable jjte000) {
    if (jjtc000) {
      this.jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      this.jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) {
		throw (RuntimeException)jjte000;
	}}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) {
		throw (ParseException)jjte000;
	}}
    }
    {if (true) {
		throw (Error)jjte000;
	}}
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  /**
   * <p>firstLine.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void firstLine() throws ParseException {
 /*@bgen(jjtree) Vars */
  final ASTVars jjtn000 = new ASTVars(JJTVARS);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
      case STRING_LITERAL:
        this.Var();
        label_2:
        while (true) {
          switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
          case 29:
            ;
            break;
          default:
            this.jj_la1[1] = this.jj_gen;
            break label_2;
          }
          this.jj_consume_token(29);
          this.Var();
        }
        break;
      default:
        this.jj_la1[2] = this.jj_gen;
        ;
      }
    } catch (final Throwable jjte000) {
    if (jjtc000) {
      this.jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      this.jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) {
		throw (RuntimeException)jjte000;
	}}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) {
		throw (ParseException)jjte000;
	}}
    }
    {if (true) {
		throw (Error)jjte000;
	}}
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//1
  /**
   * <p>resultLine.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void resultLine() throws ParseException {
 /*@bgen(jjtree) OneResult */
  final ASTOneResult jjtn000 = new ASTOneResult(JJTONERESULT);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      this.GraphTerm();
      label_3:
      while (true) {
        switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
        case 29:
          ;
          break;
        default:
          this.jj_la1[3] = this.jj_gen;
          break label_3;
        }
        this.jj_consume_token(29);
        this.GraphTerm();
      }
      this.jj_consume_token(28);
    } catch (final Throwable jjte000) {
    if (jjtc000) {
      this.jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      this.jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) {
		throw (RuntimeException)jjte000;
	}}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) {
		throw (ParseException)jjte000;
	}}
    }
    {if (true) {
		throw (Error)jjte000;
	}}
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//98
  /**
   * <p>Var.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void Var() throws ParseException {
 /*@bgen(jjtree) Var */
  final ASTVar jjtn000 = new ASTVar(JJTVAR);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);Token varName;
    try {
      varName = this.jj_consume_token(STRING_LITERAL);
    this.jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.setName(varName.image);
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//99
  /**
   * <p>GraphTerm.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void GraphTerm() throws ParseException {
 /*@bgen(jjtree) Value */
  final ASTValue jjtn000 = new ASTValue(JJTVALUE);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
      case IRI_REF:
      case TRUE:
      case FALSE:
      case BLANK_NODE_LABEL:
      case INTEGER:
      case DECIMAL:
      case DOUBLE:
      case STRING_LITERAL:
      case NIL:
      case ANON:
        switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
        case IRI_REF:
          this.IRIref();
          break;
        case STRING_LITERAL:
          this.RDFLiteral();
          break;
        case INTEGER:
        case DECIMAL:
        case DOUBLE:
          this.NumericLiteral();
          break;
        case TRUE:
        case FALSE:
          this.BooleanLiteral();
          break;
        case BLANK_NODE_LABEL:
        case ANON:
          this.BlankNode();
          break;
        case NIL:
                                                                                     final ASTNIL jjtn001 = new ASTNIL(JJTNIL);
                                                                                     final boolean jjtc001 = true;
                                                                                     this.jjtree.openNodeScope(jjtn001);
          try {
            this.jj_consume_token(NIL);
          } finally {
                                                                                     if (jjtc001) {
                                                                                       this.jjtree.closeNodeScope(jjtn001, true);
                                                                                     }
          }
          break;
        default:
          this.jj_la1[4] = this.jj_gen;
          this.jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        this.jj_la1[5] = this.jj_gen;
        ;
      }
    } catch (final Throwable jjte000) {
    if (jjtc000) {
      this.jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      this.jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) {
		throw (RuntimeException)jjte000;
	}}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) {
		throw (ParseException)jjte000;
	}}
    }
    {if (true) {
		throw (Error)jjte000;
	}}
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  /**
   * <p>RDFLiteral.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void RDFLiteral() throws ParseException {
 /*@bgen(jjtree) RDFLiteral */
  final ASTRDFLiteral jjtn000 = new ASTRDFLiteral(JJTRDFLITERAL);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      if (this.jj_2_1(2147483647)) {
        this.TypedLiteral();
      } else if (this.jj_2_2(2147483647)) {
        this.LiteralWithLangTag();
      } else {
        switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
        case STRING_LITERAL:
          this.String();
          break;
        default:
          this.jj_la1[6] = this.jj_gen;
          this.jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (final Throwable jjte000) {
          if (jjtc000) {
            this.jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            this.jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) {
				throw (RuntimeException)jjte000;
			}}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) {
				throw (ParseException)jjte000;
			}}
          }
          {if (true) {
			throw (Error)jjte000;
		}}
    } finally {
          if (jjtc000) {
            this.jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  /**
   * <p>TypedLiteral.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void TypedLiteral() throws ParseException {
 /*@bgen(jjtree) DoubleCircumflex */
  final ASTDoubleCircumflex jjtn000 = new ASTDoubleCircumflex(JJTDOUBLECIRCUMFLEX);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      this.String();
      this.jj_consume_token(30);
      this.IRIref();
    } catch (final Throwable jjte000) {
          if (jjtc000) {
            this.jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            this.jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) {
				throw (RuntimeException)jjte000;
			}}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) {
				throw (ParseException)jjte000;
			}}
          }
          {if (true) {
			throw (Error)jjte000;
		}}
    } finally {
          if (jjtc000) {
            this.jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  /**
   * <p>LiteralWithLangTag.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void LiteralWithLangTag() throws ParseException {
 /*@bgen(jjtree) LangTag */
  final ASTLangTag jjtn000 = new ASTLangTag(JJTLANGTAG);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      this.String();
      this.jj_consume_token(LANGTAG);
                               this.jjtree.closeNodeScope(jjtn000, true);
                               jjtc000 = false;
                               jjtn000.setLangTag(this.token.image);
    } catch (final Throwable jjte000) {
          if (jjtc000) {
            this.jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            this.jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) {
				throw (RuntimeException)jjte000;
			}}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) {
				throw (ParseException)jjte000;
			}}
          }
          {if (true) {
			throw (Error)jjte000;
		}}
    } finally {
          if (jjtc000) {
            this.jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//120
  /**
   * <p>NumericLiteral.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void NumericLiteral() throws ParseException {
    switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
    case INTEGER:
      this.Integer();
      break;
    case DECIMAL:
    case DOUBLE:
      this.FloatingPoint();
      break;
    default:
      this.jj_la1[7] = this.jj_gen;
      this.jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /**
   * <p>Integer.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void Integer() throws ParseException {
 /*@bgen(jjtree) Integer */
  final ASTInteger jjtn000 = new ASTInteger(JJTINTEGER);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      this.jj_consume_token(INTEGER);
                      this.jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
                      jjtn000.setStringInt((this.token.image));
    } finally {
          if (jjtc000) {
            this.jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  /**
   * <p>FloatingPoint.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void FloatingPoint() throws ParseException {
 /*@bgen(jjtree) FloatingPoint */
  final ASTFloatingPoint jjtn000 = new ASTFloatingPoint(JJTFLOATINGPOINT);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
      case DECIMAL:
        this.jj_consume_token(DECIMAL);
                      this.jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
                      jjtn000.setValue((this.token.image));
        break;
      case DOUBLE:
        this.jj_consume_token(DOUBLE);
                     this.jjtree.closeNodeScope(jjtn000, true);
                     jjtc000 = false;
                     jjtn000.setValue((this.token.image));
        break;
      default:
        this.jj_la1[8] = this.jj_gen;
        this.jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
          if (jjtc000) {
            this.jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//124
  /**
   * <p>BooleanLiteral.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void BooleanLiteral() throws ParseException {
 /*@bgen(jjtree) BooleanLiteral */
  final ASTBooleanLiteral jjtn000 = new ASTBooleanLiteral(JJTBOOLEANLITERAL);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);
    try {
      switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
      case TRUE:
        this.jj_consume_token(TRUE);
               this.jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
               jjtn000.setState(true);
        break;
      case FALSE:
        this.jj_consume_token(FALSE);
                this.jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
                jjtn000.setState(false);
        break;
      default:
        this.jj_la1[9] = this.jj_gen;
        this.jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//125
  /**
   * <p>String.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void String() throws ParseException {
 /*@bgen(jjtree) StringLiteral */
  final ASTStringLiteral jjtn000 = new ASTStringLiteral(JJTSTRINGLITERAL);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = this.jj_consume_token(STRING_LITERAL);
    this.jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.setStringLiteral("\u005c""+t.image+"\u005c"");
    } finally {
      if (jjtc000) {
        this.jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

//126
  /**
   * <p>IRIref.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void IRIref() throws ParseException {
    this.QuotedIriRef();
  }

  /**
   * <p>QuotedIriRef.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void QuotedIriRef() throws ParseException {
 /*@bgen(jjtree) QuotedURIRef */
  final ASTQuotedURIRef jjtn000 = new ASTQuotedURIRef(JJTQUOTEDURIREF);
  boolean jjtc000 = true;
  this.jjtree.openNodeScope(jjtn000);Token qRef;
    try {
      qRef = this.jj_consume_token(IRI_REF);
    this.jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.setQRef(qRef.image);
    } finally {
    if (jjtc000) {
      this.jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//128
  /**
   * <p>BlankNode.</p>
   *
   * @throws lupos.endpoint.client.formatreader.csv.ParseException if any.
   */
  final public void BlankNode() throws ParseException {
  Token t;
    switch ((this.jj_ntk==-1)?this.jj_ntk():this.jj_ntk) {
    case BLANK_NODE_LABEL:
      t = this.jj_consume_token(BLANK_NODE_LABEL);
                             final ASTBlankNode jjtn001 = new ASTBlankNode(JJTBLANKNODE);
                             boolean jjtc001 = true;
                             this.jjtree.openNodeScope(jjtn001);
      try {
                             this.jjtree.closeNodeScope(jjtn001, true);
                             jjtc001 = false;
                             jjtn001.setIdentifier((t.image));
      } finally {
                             if (jjtc001) {
                               this.jjtree.closeNodeScope(jjtn001, true);
                             }
      }
      break;
    case ANON:
     final ASTEmptyNode jjtn002 = new ASTEmptyNode(JJTEMPTYNODE);
     final boolean jjtc002 = true;
     this.jjtree.openNodeScope(jjtn002);
      try {
        this.jj_consume_token(ANON);
      } finally {
     if (jjtc002) {
       this.jjtree.closeNodeScope(jjtn002, true);
     }
      }
      break;
    default:
      this.jj_la1[10] = this.jj_gen;
      this.jj_consume_token(-1);
      throw new ParseException();
    }
  }

  private boolean jj_2_1(final int xla) {
    this.jj_la = xla; this.jj_lastpos = this.jj_scanpos = this.token;
    try { return !this.jj_3_1(); }
    catch(final LookaheadSuccess ls) { return true; }
    finally { this.jj_save(0, xla); }
  }

  private boolean jj_2_2(final int xla) {
    this.jj_la = xla; this.jj_lastpos = this.jj_scanpos = this.token;
    try { return !this.jj_3_2(); }
    catch(final LookaheadSuccess ls) { return true; }
    finally { this.jj_save(1, xla); }
  }

  private boolean jj_3_2() {
    if (this.jj_scan_token(STRING_LITERAL)) {
		return true;
	}
    if (this.jj_scan_token(LANGTAG)) {
		return true;
	}
    return false;
  }

  private boolean jj_3_1() {
    if (this.jj_scan_token(STRING_LITERAL)) {
		return true;
	}
    if (this.jj_scan_token(30)) {
		return true;
	}
    return false;
  }

  /** Generated Token Manager. */
  public CSVParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[11];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x3005bad0,0x20000000,0x8000,0x20000000,0x5bad0,0x5bad0,0x8000,0x3800,0x3000,0xc0,0x40200,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /**
   * Constructor with InputStream.
   *
   * @param stream a {@link java.io.InputStream} object.
   */
  public CSVParser(final java.io.InputStream stream) {
     this(stream, null);
  }
  /**
   * Constructor with InputStream and supplied encoding
   *
   * @param stream a {@link java.io.InputStream} object.
   * @param encoding a {@link java.lang.String} object.
   */
  public CSVParser(final java.io.InputStream stream, final String encoding) {
    try { this.jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(final java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    this.token_source = new CSVParserTokenManager(this.jj_input_stream);
    this.token = new Token();
    this.jj_ntk = -1;
    this.jj_gen = 0;
    for (int i = 0; i < 11; i++) {
		this.jj_la1[i] = -1;
	}
    for (int i = 0; i < this.jj_2_rtns.length; i++) {
		this.jj_2_rtns[i] = new JJCalls();
	}
  }

  /**
   * Reinitialise.
   *
   * @param stream a {@link java.io.InputStream} object.
   */
  public void ReInit(final java.io.InputStream stream) {
     this.ReInit(stream, null);
  }
  /**
   * Reinitialise.
   *
   * @param stream a {@link java.io.InputStream} object.
   * @param encoding a {@link java.lang.String} object.
   */
  public void ReInit(final java.io.InputStream stream, final String encoding) {
    try { this.jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(final java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    this.token_source.ReInit(this.jj_input_stream);
    this.token = new Token();
    this.jj_ntk = -1;
    this.jjtree.reset();
    this.jj_gen = 0;
    for (int i = 0; i < 11; i++) {
		this.jj_la1[i] = -1;
	}
    for (int i = 0; i < this.jj_2_rtns.length; i++) {
		this.jj_2_rtns[i] = new JJCalls();
	}
  }

  /**
   * Constructor.
   *
   * @param stream a {@link java.io.Reader} object.
   */
  public CSVParser(final java.io.Reader stream) {
    this.jj_input_stream = new JavaCharStream(stream, 1, 1);
    this.token_source = new CSVParserTokenManager(this.jj_input_stream);
    this.token = new Token();
    this.jj_ntk = -1;
    this.jj_gen = 0;
    for (int i = 0; i < 11; i++) {
		this.jj_la1[i] = -1;
	}
    for (int i = 0; i < this.jj_2_rtns.length; i++) {
		this.jj_2_rtns[i] = new JJCalls();
	}
  }

  /**
   * Reinitialise.
   *
   * @param stream a {@link java.io.Reader} object.
   */
  public void ReInit(final java.io.Reader stream) {
    this.jj_input_stream.ReInit(stream, 1, 1);
    this.token_source.ReInit(this.jj_input_stream);
    this.token = new Token();
    this.jj_ntk = -1;
    this.jjtree.reset();
    this.jj_gen = 0;
    for (int i = 0; i < 11; i++) {
		this.jj_la1[i] = -1;
	}
    for (int i = 0; i < this.jj_2_rtns.length; i++) {
		this.jj_2_rtns[i] = new JJCalls();
	}
  }

  /**
   * Constructor with generated Token Manager.
   *
   * @param tm a {@link lupos.endpoint.client.formatreader.csv.CSVParserTokenManager} object.
   */
  public CSVParser(final CSVParserTokenManager tm) {
    this.token_source = tm;
    this.token = new Token();
    this.jj_ntk = -1;
    this.jj_gen = 0;
    for (int i = 0; i < 11; i++) {
		this.jj_la1[i] = -1;
	}
    for (int i = 0; i < this.jj_2_rtns.length; i++) {
		this.jj_2_rtns[i] = new JJCalls();
	}
  }

  /**
   * Reinitialise.
   *
   * @param tm a {@link lupos.endpoint.client.formatreader.csv.CSVParserTokenManager} object.
   */
  public void ReInit(final CSVParserTokenManager tm) {
    this.token_source = tm;
    this.token = new Token();
    this.jj_ntk = -1;
    this.jjtree.reset();
    this.jj_gen = 0;
    for (int i = 0; i < 11; i++) {
		this.jj_la1[i] = -1;
	}
    for (int i = 0; i < this.jj_2_rtns.length; i++) {
		this.jj_2_rtns[i] = new JJCalls();
	}
  }

  private Token jj_consume_token(final int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = this.token).next != null) {
		this.token = this.token.next;
	} else {
		this.token = this.token.next = this.token_source.getNextToken();
	}
    this.jj_ntk = -1;
    if (this.token.kind == kind) {
      this.jj_gen++;
      if (++this.jj_gc > 100) {
        this.jj_gc = 0;
        for (int i = 0; i < this.jj_2_rtns.length; i++) {
          JJCalls c = this.jj_2_rtns[i];
          while (c != null) {
            if (c.gen < this.jj_gen) {
				c.first = null;
			}
            c = c.next;
          }
        }
      }
      return this.token;
    }
    this.token = oldToken;
    this.jj_kind = kind;
    throw this.generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(final int kind) {
    if (this.jj_scanpos == this.jj_lastpos) {
      this.jj_la--;
      if (this.jj_scanpos.next == null) {
        this.jj_lastpos = this.jj_scanpos = this.jj_scanpos.next = this.token_source.getNextToken();
      } else {
        this.jj_lastpos = this.jj_scanpos = this.jj_scanpos.next;
      }
    } else {
      this.jj_scanpos = this.jj_scanpos.next;
    }
    if (this.jj_rescan) {
      int i = 0; Token tok = this.token;
      while (tok != null && tok != this.jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) {
		this.jj_add_error_token(kind, i);
	}
    }
    if (this.jj_scanpos.kind != kind) {
		return true;
	}
    if (this.jj_la == 0 && this.jj_scanpos == this.jj_lastpos) {
		throw this.jj_ls;
	}
    return false;
  }


  /**
   * Get the next Token.
   *
   * @return a {@link lupos.endpoint.client.formatreader.csv.Token} object.
   */
  final public Token getNextToken() {
    if (this.token.next != null) {
		this.token = this.token.next;
	} else {
		this.token = this.token.next = this.token_source.getNextToken();
	}
    this.jj_ntk = -1;
    this.jj_gen++;
    return this.token;
  }

  /**
   * Get the specific Token.
   *
   * @param index a int.
   * @return a {@link lupos.endpoint.client.formatreader.csv.Token} object.
   */
  final public Token getToken(final int index) {
    Token t = this.token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) {
		t = t.next;
	} else {
		t = t.next = this.token_source.getNextToken();
	}
    }
    return t;
  }

  private int jj_ntk() {
    if ((this.jj_nt=this.token.next) == null) {
		return (this.jj_ntk = (this.token.next=this.token_source.getNextToken()).kind);
	} else {
		return (this.jj_ntk = this.jj_nt.kind);
	}
  }

  private final java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private final int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(final int kind, final int pos) {
    if (pos >= 100) {
		return;
	}
    if (pos == this.jj_endpos + 1) {
      this.jj_lasttokens[this.jj_endpos++] = kind;
    } else if (this.jj_endpos != 0) {
      this.jj_expentry = new int[this.jj_endpos];
      for (int i = 0; i < this.jj_endpos; i++) {
        this.jj_expentry[i] = this.jj_lasttokens[i];
      }
      jj_entries_loop: for (final java.util.Iterator<?> it = this.jj_expentries.iterator(); it.hasNext();) {
        final int[] oldentry = (int[])(it.next());
        if (oldentry.length == this.jj_expentry.length) {
          for (int i = 0; i < this.jj_expentry.length; i++) {
            if (oldentry[i] != this.jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          this.jj_expentries.add(this.jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) {
		this.jj_lasttokens[(this.jj_endpos = pos) - 1] = kind;
	}
    }
  }

  /**
   * Generate ParseException.
   *
   * @return a {@link lupos.endpoint.client.formatreader.csv.ParseException} object.
   */
  public ParseException generateParseException() {
    this.jj_expentries.clear();
    final boolean[] la1tokens = new boolean[31];
    if (this.jj_kind >= 0) {
      la1tokens[this.jj_kind] = true;
      this.jj_kind = -1;
    }
    for (int i = 0; i < 11; i++) {
      if (this.jj_la1[i] == this.jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 31; i++) {
      if (la1tokens[i]) {
        this.jj_expentry = new int[1];
        this.jj_expentry[0] = i;
        this.jj_expentries.add(this.jj_expentry);
      }
    }
    this.jj_endpos = 0;
    this.jj_rescan_token();
    this.jj_add_error_token(0, 0);
    final int[][] exptokseq = new int[this.jj_expentries.size()][];
    for (int i = 0; i < this.jj_expentries.size(); i++) {
      exptokseq[i] = this.jj_expentries.get(i);
    }
    return new ParseException(this.token, exptokseq, tokenImage);
  }

  /**
   * Enable tracing.
   */
  final public void enable_tracing() {
  }

  /**
   * Disable tracing.
   */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    this.jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = this.jj_2_rtns[i];
      do {
        if (p.gen > this.jj_gen) {
          this.jj_la = p.arg; this.jj_lastpos = this.jj_scanpos = p.first;
          switch (i) {
            case 0: this.jj_3_1(); break;
            case 1: this.jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(final LookaheadSuccess ls) { }
    }
    this.jj_rescan = false;
  }

  private void jj_save(final int index, final int xla) {
    JJCalls p = this.jj_2_rtns[index];
    while (p.gen > this.jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = this.jj_gen + xla - this.jj_la; p.first = this.token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
