/* Generated By:JavaCC: Do not edit this line. CSVParserTreeConstants.java Version 5.0 */
package lupos.endpoint.client.formatreader.csv;

public interface CSVParserTreeConstants
{
  public int JJTRESULT = 0;
  public int JJTVARS = 1;
  public int JJTONERESULT = 2;
  public int JJTVAR = 3;
  public int JJTVALUE = 4;
  public int JJTNIL = 5;
  public int JJTRDFLITERAL = 6;
  public int JJTDOUBLECIRCUMFLEX = 7;
  public int JJTLANGTAG = 8;
  public int JJTVOID = 9;
  public int JJTINTEGER = 10;
  public int JJTFLOATINGPOINT = 11;
  public int JJTBOOLEANLITERAL = 12;
  public int JJTSTRINGLITERAL = 13;
  public int JJTQUOTEDURIREF = 14;
  public int JJTBLANKNODE = 15;
  public int JJTEMPTYNODE = 16;


  public String[] jjtNodeName = {
    "Result",
    "Vars",
    "OneResult",
    "Var",
    "Value",
    "NIL",
    "RDFLiteral",
    "DoubleCircumflex",
    "LangTag",
    "void",
    "Integer",
    "FloatingPoint",
    "BooleanLiteral",
    "StringLiteral",
    "QuotedURIRef",
    "BlankNode",
    "EmptyNode",
  };
}
/* JavaCC - OriginalChecksum=1a9c6ecf5007abb979d053d1138df49b (do not edit this line) */
