/* Generated By:JJTree: Do not edit this line. ASTAggregation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

import java.util.Iterator;

import lupos.datastructures.bindings.Bindings;
import lupos.engine.operators.singleinput.NotBoundException;
import lupos.engine.operators.singleinput.TypeErrorException;
import lupos.engine.operators.singleinput.ExpressionEvaluation.EvaluationVisitor;

public
class ASTAggregation extends SimpleNode {

	public enum TYPE {COUNT, SUM, MIN, MAX, AVG, SAMPLE, GROUP_CONCAT};
	
	private TYPE type;
	
	private boolean distinct = false;
	
  public ASTAggregation(int id) {
    super(id);
  }

  public ASTAggregation(SPARQL1_1Parser p, int id) {
    super(p, id);
  }
  
  public void setDistinct(){
	  distinct=true;
  }

  public boolean isDistinct(){
	  return distinct;
  }
  
  public void setTYPE(TYPE type){
	  this.type=type;
  }
  
  public TYPE getTYPE(){
	  return type;
  }
  
  public String toString(){
	  return type.toString() + (distinct?" DISTINCT":"");
  }

  /** Accept the visitor. **/
    public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @SuppressWarnings({ "rawtypes", "unchecked" })
  public Object accept(EvaluationVisitor visitor, Bindings b, Object data) throws NotBoundException, TypeErrorException {
	    return visitor.evaluate(this, b, data);
  }
  
  @SuppressWarnings({ "rawtypes", "unchecked" })
  public Object applyAggregation(EvaluationVisitor visitor, Iterator<? extends Object> values){
	  switch(type){
	  default:
	  case COUNT:
		  return visitor.applyAggregationCOUNT(values);
	  case SUM:
		  return visitor.applyAggregationSUM(values);
	  case MIN:
		  return visitor.applyAggregationMIN(values);
	  case MAX:
		  return visitor.applyAggregationMAX(values);
	  case AVG:
		  return visitor.applyAggregationAVG(values);
	  case SAMPLE:
		  return visitor.applyAggregationSAMPLE(values);
	  case GROUP_CONCAT:
		  final String separator;
		  if(this.jjtGetNumChildren()==1){
			  separator = " "; 
		  } else {
			  String s = ((ASTStringLiteral)this.jjtGetChild(1)).getStringLiteral();
			  separator = s.substring(1, s.length()-1);
		  }
		  return visitor.applyAggregationGROUP_CONCAT(values, separator);
	  }
  }
}
/* JavaCC - OriginalChecksum=619ad62842466c526143b32f4ac44927 (do not edit this line) */
