/* Generated By:JJTree: Do not edit this line. ASTDescribeQuery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

public
class ASTDescribeQuery extends SimpleNode {
	private boolean describeAll;
  public ASTDescribeQuery(int id) {
    super(id);
  }

  public ASTDescribeQuery(SPARQL1_1Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
    public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public boolean isDescribeAll() {
	return describeAll;
}

public void setDescribeAll(boolean describeAll) {
	this.describeAll = describeAll;
}

@Override
public String toString() {
	// TODO Auto-generated method stub
	return super.toString()+" "+describeAll;
}

}
/* JavaCC - OriginalChecksum=ac8151324af7363ebf07d3efb9605a11 (do not edit this line) */
