/* Generated By:JJTree: Do not edit this line. ASTFloatingPoint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

import lupos.datastructures.bindings.Bindings;
import lupos.engine.operators.singleinput.NotBoundException;
import lupos.engine.operators.singleinput.TypeErrorException;
import lupos.engine.operators.singleinput.ExpressionEvaluation.EvaluationVisitor;

public
class ASTFloatingPoint extends SimpleNode {

  private String value;

  public ASTFloatingPoint(int id) {
    super(id);
  }

  public ASTFloatingPoint(SPARQL1_1Parser p, int id) {
    super(p, id);
  }


  public String getValue() {
	return value;
  }

  public void setValue(String value) {
	while(value.startsWith("+"))
		value=value.substring(1);
	this.value = value;
  }

  @Override
  public String toString() {
	return super.toString() + "  " + value;
  }

  /** Accept the visitor. **/
    public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  @SuppressWarnings({ "rawtypes", "unchecked" })
  public Object accept(EvaluationVisitor visitor, Bindings b, Object data) throws NotBoundException, TypeErrorException {
	    return visitor.evaluate(this, b, data);
  }
}
/* JavaCC - OriginalChecksum=bf18c743e56aed471d8117e069281a37 (do not edit this line) */
