/* Generated By:JJTree: Do not edit this line. ASTGroupConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

import lupos.datastructures.items.Item;
import lupos.sparql1_1.operatorgraph.SPARQL1_1OperatorgraphGeneratorVisitor;
import lupos.sparql1_1.operatorgraph.helper.OperatorConnection;

public
class ASTGroupConstraint extends SimpleNode {
  public ASTGroupConstraint(int id) {
    super(id);
  }

  public ASTGroupConstraint(SPARQL1_1Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
	    return visitor.visit(this);
	  }

  public void accept(SPARQL1_1OperatorgraphGeneratorVisitor visitor, final OperatorConnection connection, Item graphConstraint){
	    visitor.visit(this, connection, graphConstraint);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2b47c252961722292fca6fbc94749005 (do not edit this line) */
