/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

import java.math.BigInteger;

import lupos.datastructures.bindings.Bindings;
import lupos.engine.operators.singleinput.NotBoundException;
import lupos.engine.operators.singleinput.TypeErrorException;
import lupos.engine.operators.singleinput.ExpressionEvaluation.EvaluationVisitor;

public
class ASTInteger extends SimpleNode {
  
  private BigInteger value;

  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(SPARQL1_1Parser p, int id) {
    super(p, id);
  }

  public BigInteger getValue() {
	return value;
  }

  public void setValue(final BigInteger value) {
	this.value = value;
  }

  public void setValue(final int value) {
	this.value = new BigInteger("" + value);
  }

  public void setStringInt(String value) {
	while(value.startsWith("+"))
		value=value.substring(1);
	this.value = new BigInteger(value);
  }

  @Override
  public String toString() {
	return super.toString() + "  " + value;
  }
	
  /** Accept the visitor. **/
    public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @SuppressWarnings({ "rawtypes", "unchecked" })
  public Object accept(EvaluationVisitor visitor, Bindings b, Object data) throws NotBoundException, TypeErrorException {
	    return visitor.evaluate(this, b, data);
  }
}
/* JavaCC - OriginalChecksum=2a1e4045a3892e641151652f57d870e4 (do not edit this line) */
