/* Generated By:JJTree: Do not edit this line. ASTLangTag.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

public
class ASTLangTag extends SimpleNode {
	private String langTag;
  public ASTLangTag(int id) {
    super(id);
  }

  public ASTLangTag(SPARQL1_1Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
    public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public String getLangTag() {
	return langTag;
}

public void setLangTag(String langTag) {
	this.langTag = langTag;
}
@Override
public String toString() {
	return super.toString()+" "+langTag;
}
}
/* JavaCC - OriginalChecksum=697f576ef2521d37225f4efb1b07d7b4 (do not edit this line) */
