/* Generated By:JJTree: Do not edit this line. ASTMove.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

public
class ASTMove extends SimpleNode {

	private boolean silent = false;

	public void setSilent(){
		silent=true;
	}

	public boolean isSilent(){
		return silent;
	}

	public ASTMove(int id) {
		super(id);
	}

	public ASTMove(SPARQL1_1Parser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	  public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=a4c7a5595b4f4cc5aba18fbb4197c73f (do not edit this line) */
