/* Generated By:JJTree: Do not edit this line. ASTQuotedURIRef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

import lupos.datastructures.bindings.Bindings;
import lupos.datastructures.items.Item;
import lupos.datastructures.items.Variable;
import lupos.engine.operators.BasicOperator;
import lupos.engine.operators.singleinput.NotBoundException;
import lupos.engine.operators.singleinput.TypeErrorException;
import lupos.engine.operators.singleinput.ExpressionEvaluation.EvaluationVisitor;
import lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserPathVisitorStringGenerator;
import lupos.sparql1_1.operatorgraph.SPARQL1_1OperatorgraphGeneratorVisitor;
import lupos.sparql1_1.operatorgraph.helper.OperatorConnection;

public
class ASTQuotedURIRef extends SimpleNode {
	private String qRef;
  public ASTQuotedURIRef(int id) {
    super(id);
  }

  public ASTQuotedURIRef(SPARQL1_1Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
    public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
    return visitor.visit(this);
  }

  public Object jjtAccept(SPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public String accept(SPARQL1_1ParserPathVisitorStringGenerator visitor, String subject, String object){
	    return visitor.visit(this, subject, object);
  }
  
  public BasicOperator accept(SPARQL1_1OperatorgraphGeneratorVisitor visitor, OperatorConnection connection, Item graphConstraint, Variable subject, Variable object, Node subjectNode, Node objectNode) {
	    return visitor.visit(this, connection, graphConstraint, subject, object, subjectNode, objectNode);
  }

  @SuppressWarnings({ "rawtypes", "unchecked" })
  public Object accept(EvaluationVisitor visitor, Bindings b, Object data) throws NotBoundException, TypeErrorException {
	  return visitor.evaluate(this, b, data);
  }

  public String getQRef() {
	  return qRef;
  }

  public void setQRef(String qRef) {
	  this.qRef = qRef;
  }

  public String toQueryString() {
	  return "<" + this.qRef + ">";
  }

  @Override
  public String toString() {
	  // TODO Auto-generated method stub
	  return qRef;
  }
}
/* JavaCC - OriginalChecksum=e4e66b3497d767749720c42fa02ef0c0 (do not edit this line) */
