/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.sparql1_1;

public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(StreamSPARQL1_1ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String accept(lupos.optimizations.sparql2core_sparql.SPARQL1_1ParserVisitorStringGenerator visitor) {
	  return visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=d2b9dafc160c326990bbfbc192690943 (do not edit this line) */
