/* Generated By:JavaCC: Do not edit this line. SPARQL1_1ParserTreeConstants.java Version 5.0 */
package lupos.sparql1_1;

public interface SPARQL1_1ParserTreeConstants
{
  public int JJTGROUPCONSTRAINT = 0;
  public int JJTTRIPLESET = 1;
  public int JJTVOID = 2;
  public int JJTAVERBTYPE = 3;
  public int JJTQUERY = 4;
  public int JJTBASEDECL = 5;
  public int JJTPREFIXDECL = 6;
  public int JJTSELECTQUERY = 7;
  public int JJTAS = 8;
  public int JJTCONSTRUCTQUERY = 9;
  public int JJTDESCRIBEQUERY = 10;
  public int JJTASKQUERY = 11;
  public int JJTDEFAULTGRAPH = 12;
  public int JJTNAMEDGRAPH = 13;
  public int JJTGROUP = 14;
  public int JJTHAVING = 15;
  public int JJTORDERCONDITIONS = 16;
  public int JJTASCORDER = 17;
  public int JJTDESCORDER = 18;
  public int JJTLIMIT = 19;
  public int JJTOFFSET = 20;
  public int JJTBINDINGS = 21;
  public int JJTNIL = 22;
  public int JJTPLUSNODE = 23;
  public int JJTUNDEF = 24;
  public int JJTLOAD = 25;
  public int JJTCLEAR = 26;
  public int JJTDROP = 27;
  public int JJTCREATE = 28;
  public int JJTADD = 29;
  public int JJTMOVE = 30;
  public int JJTCOPY = 31;
  public int JJTINSERT = 32;
  public int JJTDELETE = 33;
  public int JJTMODIFY = 34;
  public int JJTDEFAULT = 35;
  public int JJTNAMED = 36;
  public int JJTALL = 37;
  public int JJTCONSTRUCTTEMPLATE = 38;
  public int JJTGRAPHCONSTRAINT = 39;
  public int JJTOPTIONALCONSTRAINT = 40;
  public int JJTSERVICE = 41;
  public int JJTBIND = 42;
  public int JJTMINUS = 43;
  public int JJTUNIONCONSTRAINT = 44;
  public int JJTFILTERCONSTRAINT = 45;
  public int JJTFUNCTIONCALL = 46;
  public int JJTARGUMENTS = 47;
  public int JJTEXPRESSIONLIST = 48;
  public int JJTNODESET = 49;
  public int JJTOBJECTLIST = 50;
  public int JJTPATHALTERNATIVE = 51;
  public int JJTPATHSEQUENCE = 52;
  public int JJTINVERS = 53;
  public int JJTARBITRARYOCCURENCES = 54;
  public int JJTOPTIONALOCCURENCE = 55;
  public int JJTARBITRARYOCCURENCESNOTZERO = 56;
  public int JJTGIVENOCCURENCES = 57;
  public int JJTNEGATEDPATH = 58;
  public int JJTINTEGER = 59;
  public int JJTBLANKNODEPROPERTYLIST = 60;
  public int JJTCOLLECTION = 61;
  public int JJTVAR = 62;
  public int JJTORNODE = 63;
  public int JJTANDNODE = 64;
  public int JJTEQUALSNODE = 65;
  public int JJTNOTEQUALSNODE = 66;
  public int JJTLESSTHANNODE = 67;
  public int JJTLESSTHANEQUALSNODE = 68;
  public int JJTGREATERTHANNODE = 69;
  public int JJTGREATERTHANEQUALSNODE = 70;
  public int JJTINNODE = 71;
  public int JJTNOTINNODE = 72;
  public int JJTADDITIONNODE = 73;
  public int JJTSUBTRACTIONNODE = 74;
  public int JJTMULTIPLICATIONNODE = 75;
  public int JJTDIVISIONNODE = 76;
  public int JJTNOTNODE = 77;
  public int JJTMINUSNODE = 78;
  public int JJTSTRFUNCNODE = 79;
  public int JJTLANGFUNCNODE = 80;
  public int JJTLANGMATCHESFUNCNODE = 81;
  public int JJTDATATYPEFUNCNODE = 82;
  public int JJTBOUNDFUNCNODE = 83;
  public int JJTIRIFUNCNODE = 84;
  public int JJTURIFUNCNODE = 85;
  public int JJTBNODEFUNCNODE = 86;
  public int JJTRANDFUNCNODE = 87;
  public int JJTABSFUNCNODE = 88;
  public int JJTCEILFUNCNODE = 89;
  public int JJTFLOORFUNCNODE = 90;
  public int JJTROUNDFUNCNODE = 91;
  public int JJTCONCATFUNCNODE = 92;
  public int JJTSTRLENFUNCNODE = 93;
  public int JJTUCASEFUNCNODE = 94;
  public int JJTLCASEFUNCNODE = 95;
  public int JJTENCODEFORURIFUNCNODE = 96;
  public int JJTCONTAINSFUNCNODE = 97;
  public int JJTSTRSTARTSFUNCNODE = 98;
  public int JJTSTRENDSFUNCNODE = 99;
  public int JJTSTRBEFOREFUNCNODE = 100;
  public int JJTSTRAFTERFUNCNODE = 101;
  public int JJTYEARFUNCNODE = 102;
  public int JJTMONTHFUNCNODE = 103;
  public int JJTDAYFUNCNODE = 104;
  public int JJTHOURSFUNCNODE = 105;
  public int JJTMINUTESFUNCNODE = 106;
  public int JJTSECONDSFUNCNODE = 107;
  public int JJTTIMEZONEFUNCNODE = 108;
  public int JJTTZFUNCNODE = 109;
  public int JJTNOWFUNCNODE = 110;
  public int JJTMD5FUNCNODE = 111;
  public int JJTSHA1FUNCNODE = 112;
  public int JJTSHA256FUNCNODE = 113;
  public int JJTSHA384FUNCNODE = 114;
  public int JJTSHA512FUNCNODE = 115;
  public int JJTCOALESCEFUNCNODE = 116;
  public int JJTIFFUNCNODE = 117;
  public int JJTSTRLANGFUNCNODE = 118;
  public int JJTSTRDTFUNCNODE = 119;
  public int JJTSAMETERMFUNCNODE = 120;
  public int JJTISIRIFUNCNODE = 121;
  public int JJTISURIFUNCNODE = 122;
  public int JJTISBLANKFUNCNODE = 123;
  public int JJTISLITERALFUNCNODE = 124;
  public int JJTISNUMERICFUNCNODE = 125;
  public int JJTREGEXFUNCNODE = 126;
  public int JJTSUBSTRINGFUNCNODE = 127;
  public int JJTSTRREPLACEFUNCNODE = 128;
  public int JJTEXISTS = 129;
  public int JJTNOTEXISTS = 130;
  public int JJTAGGREGATION = 131;
  public int JJTRDFLITERAL = 132;
  public int JJTDOUBLECIRCUMFLEX = 133;
  public int JJTLANGTAG = 134;
  public int JJTFLOATINGPOINT = 135;
  public int JJTBOOLEANLITERAL = 136;
  public int JJTSTRINGLITERAL = 137;
  public int JJTQUOTEDURIREF = 138;
  public int JJTQNAME = 139;
  public int JJTBLANKNODE = 140;
  public int JJTEMPTYNODE = 141;


  public String[] jjtNodeName = {
    "GroupConstraint",
    "TripleSet",
    "void",
    "AVerbType",
    "Query",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "As",
    "ConstructQuery",
    "DescribeQuery",
    "AskQuery",
    "DefaultGraph",
    "NamedGraph",
    "Group",
    "Having",
    "OrderConditions",
    "AscOrder",
    "DescOrder",
    "Limit",
    "Offset",
    "Bindings",
    "NIL",
    "PlusNode",
    "Undef",
    "Load",
    "Clear",
    "Drop",
    "Create",
    "Add",
    "Move",
    "Copy",
    "Insert",
    "Delete",
    "Modify",
    "Default",
    "Named",
    "All",
    "ConstructTemplate",
    "GraphConstraint",
    "OptionalConstraint",
    "Service",
    "Bind",
    "Minus",
    "UnionConstraint",
    "FilterConstraint",
    "FunctionCall",
    "Arguments",
    "ExpressionList",
    "NodeSet",
    "ObjectList",
    "PathAlternative",
    "PathSequence",
    "Invers",
    "ArbitraryOccurences",
    "OptionalOccurence",
    "ArbitraryOccurencesNotZero",
    "GivenOccurences",
    "NegatedPath",
    "Integer",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "OrNode",
    "AndNode",
    "EqualsNode",
    "NotEqualsNode",
    "LessThanNode",
    "LessThanEqualsNode",
    "GreaterThanNode",
    "GreaterThanEqualsNode",
    "InNode",
    "NotInNode",
    "AdditionNode",
    "SubtractionNode",
    "MultiplicationNode",
    "DivisionNode",
    "NotNode",
    "MinusNode",
    "StrFuncNode",
    "LangFuncNode",
    "LangMatchesFuncNode",
    "DataTypeFuncNode",
    "BoundFuncNode",
    "IriFuncNode",
    "UriFuncNode",
    "BnodeFuncNode",
    "RandFuncNode",
    "ABSFuncNode",
    "CeilFuncNode",
    "FloorFuncNode",
    "RoundFuncNode",
    "ConcatFuncNode",
    "StrlenFuncNode",
    "UcaseFuncNode",
    "LcaseFuncNode",
    "EncodeForUriFuncNode",
    "ContainsFuncNode",
    "StrstartsFuncNode",
    "StrEndsFuncNode",
    "StrBeforeFuncNode",
    "StrAfterFuncNode",
    "YearFuncNode",
    "MonthFuncNode",
    "DayFuncNode",
    "HoursFuncNode",
    "MinutesFuncNode",
    "SecondsFuncNode",
    "TimeZoneFuncNode",
    "TzFuncNode",
    "NowFuncNode",
    "MD5FuncNode",
    "SHA1FuncNode",
    "SHA256FuncNode",
    "SHA384FuncNode",
    "SHA512FuncNode",
    "CoalesceFuncNode",
    "IfFuncNode",
    "StrLangFuncNode",
    "StrdtFuncNode",
    "SameTermFuncNode",
    "isIRIFuncNode",
    "isURIFuncNode",
    "isBlankFuncNode",
    "isLiteralFuncNode",
    "isNumericFuncNode",
    "RegexFuncNode",
    "SubstringFuncNode",
    "StrReplaceFuncNode",
    "Exists",
    "NotExists",
    "Aggregation",
    "RDFLiteral",
    "DoubleCircumflex",
    "LangTag",
    "FloatingPoint",
    "BooleanLiteral",
    "StringLiteral",
    "QuotedURIRef",
    "QName",
    "BlankNode",
    "EmptyNode",
  };
}
/* JavaCC - OriginalChecksum=b66e34d78a88339caa7cb2d1e436f138 (do not edit this line) */
