/**
 * Copyright (c) 2007-2015, Institute of Information Systems (Sven Groppe and contributors of LUPOSDATE), University of Luebeck
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 	- Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * 	  disclaimer.
 * 	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * 	  following disclaimer in the documentation and/or other materials provided with the distribution.
 * 	- Neither the name of the University of Luebeck nor the names of its contributors may be used to endorse or promote
 * 	  products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* Generated By:JavaCC: Do not edit this line. SPARQL1_1ParserTreeConstants.java Version 5.0 */
package lupos.sparql1_1;
public interface SPARQL1_1ParserTreeConstants
{
  /** Constant <code>JJTGROUPCONSTRAINT=0</code> */
  public int JJTGROUPCONSTRAINT = 0;
  /** Constant <code>JJTTRIPLESET=1</code> */
  public int JJTTRIPLESET = 1;
  /** Constant <code>JJTVOID=2</code> */
  public int JJTVOID = 2;
  /** Constant <code>JJTAVERBTYPE=3</code> */
  public int JJTAVERBTYPE = 3;
  /** Constant <code>JJTQUERY=4</code> */
  public int JJTQUERY = 4;
  /** Constant <code>JJTBASEDECL=5</code> */
  public int JJTBASEDECL = 5;
  /** Constant <code>JJTPREFIXDECL=6</code> */
  public int JJTPREFIXDECL = 6;
  /** Constant <code>JJTSELECTQUERY=7</code> */
  public int JJTSELECTQUERY = 7;
  /** Constant <code>JJTAS=8</code> */
  public int JJTAS = 8;
  /** Constant <code>JJTCONSTRUCTQUERY=9</code> */
  public int JJTCONSTRUCTQUERY = 9;
  /** Constant <code>JJTDESCRIBEQUERY=10</code> */
  public int JJTDESCRIBEQUERY = 10;
  /** Constant <code>JJTASKQUERY=11</code> */
  public int JJTASKQUERY = 11;
  /** Constant <code>JJTDEFAULTGRAPH=12</code> */
  public int JJTDEFAULTGRAPH = 12;
  /** Constant <code>JJTNAMEDGRAPH=13</code> */
  public int JJTNAMEDGRAPH = 13;
  /** Constant <code>JJTGROUP=14</code> */
  public int JJTGROUP = 14;
  /** Constant <code>JJTHAVING=15</code> */
  public int JJTHAVING = 15;
  /** Constant <code>JJTORDERCONDITIONS=16</code> */
  public int JJTORDERCONDITIONS = 16;
  /** Constant <code>JJTASCORDER=17</code> */
  public int JJTASCORDER = 17;
  /** Constant <code>JJTDESCORDER=18</code> */
  public int JJTDESCORDER = 18;
  /** Constant <code>JJTLIMIT=19</code> */
  public int JJTLIMIT = 19;
  /** Constant <code>JJTOFFSET=20</code> */
  public int JJTOFFSET = 20;
  /** Constant <code>JJTBINDINGS=21</code> */
  public int JJTBINDINGS = 21;
  /** Constant <code>JJTPLUSNODE=22</code> */
  public int JJTPLUSNODE = 22;
  /** Constant <code>JJTUNDEF=23</code> */
  public int JJTUNDEF = 23;
  /** Constant <code>JJTLOAD=24</code> */
  public int JJTLOAD = 24;
  /** Constant <code>JJTCLEAR=25</code> */
  public int JJTCLEAR = 25;
  /** Constant <code>JJTDROP=26</code> */
  public int JJTDROP = 26;
  /** Constant <code>JJTCREATE=27</code> */
  public int JJTCREATE = 27;
  /** Constant <code>JJTADD=28</code> */
  public int JJTADD = 28;
  /** Constant <code>JJTMOVE=29</code> */
  public int JJTMOVE = 29;
  /** Constant <code>JJTCOPY=30</code> */
  public int JJTCOPY = 30;
  /** Constant <code>JJTINSERT=31</code> */
  public int JJTINSERT = 31;
  /** Constant <code>JJTDELETE=32</code> */
  public int JJTDELETE = 32;
  /** Constant <code>JJTMODIFY=33</code> */
  public int JJTMODIFY = 33;
  /** Constant <code>JJTDEFAULT=34</code> */
  public int JJTDEFAULT = 34;
  /** Constant <code>JJTNAMED=35</code> */
  public int JJTNAMED = 35;
  /** Constant <code>JJTALL=36</code> */
  public int JJTALL = 36;
  /** Constant <code>JJTCONSTRUCTTEMPLATE=37</code> */
  public int JJTCONSTRUCTTEMPLATE = 37;
  /** Constant <code>JJTGRAPHCONSTRAINT=38</code> */
  public int JJTGRAPHCONSTRAINT = 38;
  /** Constant <code>JJTOPTIONALCONSTRAINT=39</code> */
  public int JJTOPTIONALCONSTRAINT = 39;
  /** Constant <code>JJTSERVICE=40</code> */
  public int JJTSERVICE = 40;
  /** Constant <code>JJTBIND=41</code> */
  public int JJTBIND = 41;
  /** Constant <code>JJTMINUS=42</code> */
  public int JJTMINUS = 42;
  /** Constant <code>JJTUNIONCONSTRAINT=43</code> */
  public int JJTUNIONCONSTRAINT = 43;
  /** Constant <code>JJTFILTERCONSTRAINT=44</code> */
  public int JJTFILTERCONSTRAINT = 44;
  /** Constant <code>JJTFUNCTIONCALL=45</code> */
  public int JJTFUNCTIONCALL = 45;
  /** Constant <code>JJTARGUMENTS=46</code> */
  public int JJTARGUMENTS = 46;
  /** Constant <code>JJTEXPRESSIONLIST=47</code> */
  public int JJTEXPRESSIONLIST = 47;
  /** Constant <code>JJTNODESET=48</code> */
  public int JJTNODESET = 48;
  /** Constant <code>JJTOBJECTLIST=49</code> */
  public int JJTOBJECTLIST = 49;
  /** Constant <code>JJTPATHALTERNATIVE=50</code> */
  public int JJTPATHALTERNATIVE = 50;
  /** Constant <code>JJTPATHSEQUENCE=51</code> */
  public int JJTPATHSEQUENCE = 51;
  /** Constant <code>JJTINVERS=52</code> */
  public int JJTINVERS = 52;
  /** Constant <code>JJTARBITRARYOCCURENCES=53</code> */
  public int JJTARBITRARYOCCURENCES = 53;
  /** Constant <code>JJTOPTIONALOCCURENCE=54</code> */
  public int JJTOPTIONALOCCURENCE = 54;
  /** Constant <code>JJTARBITRARYOCCURENCESNOTZERO=55</code> */
  public int JJTARBITRARYOCCURENCESNOTZERO = 55;
  /** Constant <code>JJTNEGATEDPATH=56</code> */
  public int JJTNEGATEDPATH = 56;
  /** Constant <code>JJTINTEGER=57</code> */
  public int JJTINTEGER = 57;
  /** Constant <code>JJTBLANKNODEPROPERTYLIST=58</code> */
  public int JJTBLANKNODEPROPERTYLIST = 58;
  /** Constant <code>JJTCOLLECTION=59</code> */
  public int JJTCOLLECTION = 59;
  /** Constant <code>JJTVAR=60</code> */
  public int JJTVAR = 60;
  /** Constant <code>JJTNIL=61</code> */
  public int JJTNIL = 61;
  /** Constant <code>JJTORNODE=62</code> */
  public int JJTORNODE = 62;
  /** Constant <code>JJTANDNODE=63</code> */
  public int JJTANDNODE = 63;
  /** Constant <code>JJTEQUALSNODE=64</code> */
  public int JJTEQUALSNODE = 64;
  /** Constant <code>JJTNOTEQUALSNODE=65</code> */
  public int JJTNOTEQUALSNODE = 65;
  /** Constant <code>JJTLESSTHANNODE=66</code> */
  public int JJTLESSTHANNODE = 66;
  /** Constant <code>JJTGREATERTHANNODE=67</code> */
  public int JJTGREATERTHANNODE = 67;
  /** Constant <code>JJTLESSTHANEQUALSNODE=68</code> */
  public int JJTLESSTHANEQUALSNODE = 68;
  /** Constant <code>JJTGREATERTHANEQUALSNODE=69</code> */
  public int JJTGREATERTHANEQUALSNODE = 69;
  /** Constant <code>JJTINNODE=70</code> */
  public int JJTINNODE = 70;
  /** Constant <code>JJTNOTINNODE=71</code> */
  public int JJTNOTINNODE = 71;
  /** Constant <code>JJTADDITIONNODE=72</code> */
  public int JJTADDITIONNODE = 72;
  /** Constant <code>JJTSUBTRACTIONNODE=73</code> */
  public int JJTSUBTRACTIONNODE = 73;
  /** Constant <code>JJTMULTIPLICATIONNODE=74</code> */
  public int JJTMULTIPLICATIONNODE = 74;
  /** Constant <code>JJTDIVISIONNODE=75</code> */
  public int JJTDIVISIONNODE = 75;
  /** Constant <code>JJTNOTNODE=76</code> */
  public int JJTNOTNODE = 76;
  /** Constant <code>JJTMINUSNODE=77</code> */
  public int JJTMINUSNODE = 77;
  /** Constant <code>JJTSTRFUNCNODE=78</code> */
  public int JJTSTRFUNCNODE = 78;
  /** Constant <code>JJTLANGFUNCNODE=79</code> */
  public int JJTLANGFUNCNODE = 79;
  /** Constant <code>JJTLANGMATCHESFUNCNODE=80</code> */
  public int JJTLANGMATCHESFUNCNODE = 80;
  /** Constant <code>JJTDATATYPEFUNCNODE=81</code> */
  public int JJTDATATYPEFUNCNODE = 81;
  /** Constant <code>JJTBOUNDFUNCNODE=82</code> */
  public int JJTBOUNDFUNCNODE = 82;
  /** Constant <code>JJTIRIFUNCNODE=83</code> */
  public int JJTIRIFUNCNODE = 83;
  /** Constant <code>JJTURIFUNCNODE=84</code> */
  public int JJTURIFUNCNODE = 84;
  /** Constant <code>JJTBNODEFUNCNODE=85</code> */
  public int JJTBNODEFUNCNODE = 85;
  /** Constant <code>JJTRANDFUNCNODE=86</code> */
  public int JJTRANDFUNCNODE = 86;
  /** Constant <code>JJTABSFUNCNODE=87</code> */
  public int JJTABSFUNCNODE = 87;
  /** Constant <code>JJTCEILFUNCNODE=88</code> */
  public int JJTCEILFUNCNODE = 88;
  /** Constant <code>JJTFLOORFUNCNODE=89</code> */
  public int JJTFLOORFUNCNODE = 89;
  /** Constant <code>JJTROUNDFUNCNODE=90</code> */
  public int JJTROUNDFUNCNODE = 90;
  /** Constant <code>JJTCONCATFUNCNODE=91</code> */
  public int JJTCONCATFUNCNODE = 91;
  /** Constant <code>JJTSTRLENFUNCNODE=92</code> */
  public int JJTSTRLENFUNCNODE = 92;
  /** Constant <code>JJTUCASEFUNCNODE=93</code> */
  public int JJTUCASEFUNCNODE = 93;
  /** Constant <code>JJTLCASEFUNCNODE=94</code> */
  public int JJTLCASEFUNCNODE = 94;
  /** Constant <code>JJTENCODEFORURIFUNCNODE=95</code> */
  public int JJTENCODEFORURIFUNCNODE = 95;
  /** Constant <code>JJTCONTAINSFUNCNODE=96</code> */
  public int JJTCONTAINSFUNCNODE = 96;
  /** Constant <code>JJTSTRSTARTSFUNCNODE=97</code> */
  public int JJTSTRSTARTSFUNCNODE = 97;
  /** Constant <code>JJTSTRENDSFUNCNODE=98</code> */
  public int JJTSTRENDSFUNCNODE = 98;
  /** Constant <code>JJTSTRBEFOREFUNCNODE=99</code> */
  public int JJTSTRBEFOREFUNCNODE = 99;
  /** Constant <code>JJTSTRAFTERFUNCNODE=100</code> */
  public int JJTSTRAFTERFUNCNODE = 100;
  /** Constant <code>JJTYEARFUNCNODE=101</code> */
  public int JJTYEARFUNCNODE = 101;
  /** Constant <code>JJTMONTHFUNCNODE=102</code> */
  public int JJTMONTHFUNCNODE = 102;
  /** Constant <code>JJTDAYFUNCNODE=103</code> */
  public int JJTDAYFUNCNODE = 103;
  /** Constant <code>JJTHOURSFUNCNODE=104</code> */
  public int JJTHOURSFUNCNODE = 104;
  /** Constant <code>JJTMINUTESFUNCNODE=105</code> */
  public int JJTMINUTESFUNCNODE = 105;
  /** Constant <code>JJTSECONDSFUNCNODE=106</code> */
  public int JJTSECONDSFUNCNODE = 106;
  /** Constant <code>JJTTIMEZONEFUNCNODE=107</code> */
  public int JJTTIMEZONEFUNCNODE = 107;
  /** Constant <code>JJTTZFUNCNODE=108</code> */
  public int JJTTZFUNCNODE = 108;
  /** Constant <code>JJTNOWFUNCNODE=109</code> */
  public int JJTNOWFUNCNODE = 109;
  /** Constant <code>JJTUUIDFUNCNODE=110</code> */
  public int JJTUUIDFUNCNODE = 110;
  /** Constant <code>JJTSTRUUIDFUNCNODE=111</code> */
  public int JJTSTRUUIDFUNCNODE = 111;
  /** Constant <code>JJTMD5FUNCNODE=112</code> */
  public int JJTMD5FUNCNODE = 112;
  /** Constant <code>JJTSHA1FUNCNODE=113</code> */
  public int JJTSHA1FUNCNODE = 113;
  /** Constant <code>JJTSHA256FUNCNODE=114</code> */
  public int JJTSHA256FUNCNODE = 114;
  /** Constant <code>JJTSHA384FUNCNODE=115</code> */
  public int JJTSHA384FUNCNODE = 115;
  /** Constant <code>JJTSHA512FUNCNODE=116</code> */
  public int JJTSHA512FUNCNODE = 116;
  /** Constant <code>JJTCOALESCEFUNCNODE=117</code> */
  public int JJTCOALESCEFUNCNODE = 117;
  /** Constant <code>JJTIFFUNCNODE=118</code> */
  public int JJTIFFUNCNODE = 118;
  /** Constant <code>JJTSTRLANGFUNCNODE=119</code> */
  public int JJTSTRLANGFUNCNODE = 119;
  /** Constant <code>JJTSTRDTFUNCNODE=120</code> */
  public int JJTSTRDTFUNCNODE = 120;
  /** Constant <code>JJTSAMETERMFUNCNODE=121</code> */
  public int JJTSAMETERMFUNCNODE = 121;
  /** Constant <code>JJTISIRIFUNCNODE=122</code> */
  public int JJTISIRIFUNCNODE = 122;
  /** Constant <code>JJTISURIFUNCNODE=123</code> */
  public int JJTISURIFUNCNODE = 123;
  /** Constant <code>JJTISBLANKFUNCNODE=124</code> */
  public int JJTISBLANKFUNCNODE = 124;
  /** Constant <code>JJTISLITERALFUNCNODE=125</code> */
  public int JJTISLITERALFUNCNODE = 125;
  /** Constant <code>JJTISNUMERICFUNCNODE=126</code> */
  public int JJTISNUMERICFUNCNODE = 126;
  /** Constant <code>JJTREGEXFUNCNODE=127</code> */
  public int JJTREGEXFUNCNODE = 127;
  /** Constant <code>JJTSUBSTRINGFUNCNODE=128</code> */
  public int JJTSUBSTRINGFUNCNODE = 128;
  /** Constant <code>JJTSTRREPLACEFUNCNODE=129</code> */
  public int JJTSTRREPLACEFUNCNODE = 129;
  /** Constant <code>JJTEXISTS=130</code> */
  public int JJTEXISTS = 130;
  /** Constant <code>JJTNOTEXISTS=131</code> */
  public int JJTNOTEXISTS = 131;
  /** Constant <code>JJTAGGREGATION=132</code> */
  public int JJTAGGREGATION = 132;
  /** Constant <code>JJTRDFLITERAL=133</code> */
  public int JJTRDFLITERAL = 133;
  /** Constant <code>JJTDOUBLECIRCUMFLEX=134</code> */
  public int JJTDOUBLECIRCUMFLEX = 134;
  /** Constant <code>JJTLANGTAG=135</code> */
  public int JJTLANGTAG = 135;
  /** Constant <code>JJTFLOATINGPOINT=136</code> */
  public int JJTFLOATINGPOINT = 136;
  /** Constant <code>JJTBOOLEANLITERAL=137</code> */
  public int JJTBOOLEANLITERAL = 137;
  /** Constant <code>JJTSTRINGLITERAL=138</code> */
  public int JJTSTRINGLITERAL = 138;
  /** Constant <code>JJTQUOTEDURIREF=139</code> */
  public int JJTQUOTEDURIREF = 139;
  /** Constant <code>JJTQNAME=140</code> */
  public int JJTQNAME = 140;
  /** Constant <code>JJTBLANKNODE=141</code> */
  public int JJTBLANKNODE = 141;
  /** Constant <code>JJTEMPTYNODE=142</code> */
  public int JJTEMPTYNODE = 142;


  /** Constant <code>jjtNodeName="{GroupConstraint,TripleSet,void,AVerbTy"{trunked}</code> */
  public String[] jjtNodeName = {
    "GroupConstraint",
    "TripleSet",
    "void",
    "AVerbType",
    "Query",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "As",
    "ConstructQuery",
    "DescribeQuery",
    "AskQuery",
    "DefaultGraph",
    "NamedGraph",
    "Group",
    "Having",
    "OrderConditions",
    "AscOrder",
    "DescOrder",
    "Limit",
    "Offset",
    "Bindings",
    "PlusNode",
    "Undef",
    "Load",
    "Clear",
    "Drop",
    "Create",
    "Add",
    "Move",
    "Copy",
    "Insert",
    "Delete",
    "Modify",
    "Default",
    "Named",
    "All",
    "ConstructTemplate",
    "GraphConstraint",
    "OptionalConstraint",
    "Service",
    "Bind",
    "Minus",
    "UnionConstraint",
    "FilterConstraint",
    "FunctionCall",
    "Arguments",
    "ExpressionList",
    "NodeSet",
    "ObjectList",
    "PathAlternative",
    "PathSequence",
    "Invers",
    "ArbitraryOccurences",
    "OptionalOccurence",
    "ArbitraryOccurencesNotZero",
    "NegatedPath",
    "Integer",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "NIL",
    "OrNode",
    "AndNode",
    "EqualsNode",
    "NotEqualsNode",
    "LessThanNode",
    "GreaterThanNode",
    "LessThanEqualsNode",
    "GreaterThanEqualsNode",
    "InNode",
    "NotInNode",
    "AdditionNode",
    "SubtractionNode",
    "MultiplicationNode",
    "DivisionNode",
    "NotNode",
    "MinusNode",
    "StrFuncNode",
    "LangFuncNode",
    "LangMatchesFuncNode",
    "DataTypeFuncNode",
    "BoundFuncNode",
    "IriFuncNode",
    "UriFuncNode",
    "BnodeFuncNode",
    "RandFuncNode",
    "ABSFuncNode",
    "CeilFuncNode",
    "FloorFuncNode",
    "RoundFuncNode",
    "ConcatFuncNode",
    "StrlenFuncNode",
    "UcaseFuncNode",
    "LcaseFuncNode",
    "EncodeForUriFuncNode",
    "ContainsFuncNode",
    "StrstartsFuncNode",
    "StrEndsFuncNode",
    "StrBeforeFuncNode",
    "StrAfterFuncNode",
    "YearFuncNode",
    "MonthFuncNode",
    "DayFuncNode",
    "HoursFuncNode",
    "MinutesFuncNode",
    "SecondsFuncNode",
    "TimeZoneFuncNode",
    "TzFuncNode",
    "NowFuncNode",
    "UUIDFuncNode",
    "STRUUIDFuncNode",
    "MD5FuncNode",
    "SHA1FuncNode",
    "SHA256FuncNode",
    "SHA384FuncNode",
    "SHA512FuncNode",
    "CoalesceFuncNode",
    "IfFuncNode",
    "StrLangFuncNode",
    "StrdtFuncNode",
    "SameTermFuncNode",
    "isIRIFuncNode",
    "isURIFuncNode",
    "isBlankFuncNode",
    "isLiteralFuncNode",
    "isNumericFuncNode",
    "RegexFuncNode",
    "SubstringFuncNode",
    "StrReplaceFuncNode",
    "Exists",
    "NotExists",
    "Aggregation",
    "RDFLiteral",
    "DoubleCircumflex",
    "LangTag",
    "FloatingPoint",
    "BooleanLiteral",
    "StringLiteral",
    "QuotedURIRef",
    "QName",
    "BlankNode",
    "EmptyNode",
  };
}
/* JavaCC - OriginalChecksum=1891a5c41359ddd4322f03f7d270097c (do not edit this line) */
