/* Generated By:JJTree&JavaCC: Do not edit this line. StreamSPARQL1_1ParserConstants.java */
package lupos.sparql1_1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StreamSPARQL1_1ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IRI_REF = 10;
  /** RegularExpression Id. */
  int VARNAME = 11;
  /** RegularExpression Id. */
  int PNAME_NS = 12;
  /** RegularExpression Id. */
  int PNAME_LN = 13;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int VAR1 = 16;
  /** RegularExpression Id. */
  int VAR2 = 17;
  /** RegularExpression Id. */
  int LANGTAG = 18;
  /** RegularExpression Id. */
  int INTEGER = 19;
  /** RegularExpression Id. */
  int DECIMAL = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int EXPONENT = 22;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 23;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 24;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 25;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 26;
  /** RegularExpression Id. */
  int NIL = 27;
  /** RegularExpression Id. */
  int WS = 28;
  /** RegularExpression Id. */
  int ANON = 29;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 30;
  /** RegularExpression Id. */
  int PN_CHARS_U = 31;
  /** RegularExpression Id. */
  int PN_CHARS = 32;
  /** RegularExpression Id. */
  int PN_PREFIX = 33;
  /** RegularExpression Id. */
  int PN_LOCAL = 34;
  /** RegularExpression Id. */
  int PLX = 35;
  /** RegularExpression Id. */
  int PERCENT = 36;
  /** RegularExpression Id. */
  int HEX = 37;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\".\"",
    "\"}\"",
    "\"a\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 9>",
    "<IRI_REF>",
    "<VARNAME>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<NIL>",
    "<WS>",
    "<ANON>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<PLX>",
    "<PERCENT>",
    "<HEX>",
    "<PN_LOCAL_ESC>",
    "\"BASE\"",
    "\"PREFIX\"",
    "\"SELECT\"",
    "\"DISTINCT\"",
    "\"REDUCED\"",
    "\"*\"",
    "\"(\"",
    "\"AS\"",
    "\")\"",
    "\"CONSTRUCT\"",
    "\"WHERE\"",
    "\"DESCRIBE\"",
    "\"ASK\"",
    "\"STREAM\"",
    "\"INTERMEDIATERESULT\"",
    "\"DURATION\"",
    "\"TRIPLES\"",
    "\"WINDOW\"",
    "\"START\"",
    "\"END\"",
    "\"TYPE\"",
    "\"SLIDINGDURATION\"",
    "\"SLIDINGTRIPLES\"",
    "\"FROM\"",
    "\"NAMED\"",
    "\"GROUP\"",
    "\"BY\"",
    "\"HAVING\"",
    "\"ORDER\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"LIMIT\"",
    "\"OFFSET\"",
    "\"BINDINGS\"",
    "\"UNDEF\"",
    "\";\"",
    "\"INSERT\"",
    "\"DATA\"",
    "\"DELETE\"",
    "\"LOAD\"",
    "\"SILENT\"",
    "\"INTO\"",
    "\"CLEAR\"",
    "\"DROP\"",
    "\"CREATE\"",
    "\"ADD\"",
    "\"TO\"",
    "\"MOVE\"",
    "\"COPY\"",
    "\"WITH\"",
    "\"USING\"",
    "\"DEFAULT\"",
    "\"GRAPH\"",
    "\"ALL\"",
    "\"OPTIONAL\"",
    "\"SERVICE\"",
    "\"BIND\"",
    "\"MINUS\"",
    "\"UNION\"",
    "\"FILTER\"",
    "\",\"",
    "\"[\"",
    "\"|\"",
    "\"/\"",
    "\"^\"",
    "\"?\"",
    "\"+\"",
    "\"!\"",
    "\"]\"",
    "\"||\"",
    "\"&&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"IN\"",
    "\"NOT\"",
    "\"-\"",
    "\"STR\"",
    "\"LANG\"",
    "\"LANGMATCHES\"",
    "\"DATATYPE\"",
    "\"BOUND\"",
    "\"IRI\"",
    "\"URI\"",
    "\"BNODE\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"STRLEN\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"COALESCE\"",
    "\"IF\"",
    "\"STRLANG\"",
    "\"STRDT\"",
    "\"sameTerm\"",
    "\"isIRI\"",
    "\"isURI\"",
    "\"isBLANK\"",
    "\"isLITERAL\"",
    "\"isNUMERIC\"",
    "\"REGEX\"",
    "\"SUBSTR\"",
    "\"REPLACE\"",
    "\"EXISTS\"",
    "\"COUNT\"",
    "\"SUM\"",
    "\"MIN\"",
    "\"MAX\"",
    "\"AVG\"",
    "\"SAMPLE\"",
    "\"GROUP_CONCAT\"",
    "\"SEPARATOR\"",
    "\"^^\"",
    "\"true\"",
    "\"false\"",
  };

}
