/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.tsv;

public class ASTBooleanLiteral extends SimpleNode {

	private boolean state;

	public ASTBooleanLiteral(int id) {
		super(id);
	}

	public ASTBooleanLiteral(TSVParser p, int id) {
		super(p, id);
	}

	public boolean getState() {
		return state;
	}

	public void setState(final boolean booleanLit) {
		this.state = booleanLit;
	}

	@Override
	public String toString() {
		return super.toString() + "  " + state;
	}

	/** Accept the visitor. **/
	public Object jjtAccept(TSVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=524bbdfd5aff773e93eed17dc81033ce (do not edit this line) */
