/* Generated By:JJTree: Do not edit this line. ASTRDFLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lupos.endpoint.client.formatreader.tsv;

public
class ASTRDFLiteral extends SimpleNode {
  public ASTRDFLiteral(int id) {
    super(id);
  }

  public ASTRDFLiteral(TSVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TSVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=32162bf7c841b1d3a2465edc3ec12365 (do not edit this line) */
