
/**
 * Copyright (c) 2007-2015, Institute of Information Systems (Sven Groppe and contributors of LUPOSDATE), University of Luebeck
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 	- Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * 	  disclaimer.
 * 	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * 	  following disclaimer in the documentation and/or other materials provided with the distribution.
 * 	- Neither the name of the University of Luebeck nor the names of its contributors may be used to endorse or promote
 * 	  products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author groppe
 * @version $Id: $Id
 */
/* Generated By:JavaCC: Do not edit this line. TSVParserTreeConstants.java Version 5.0 */
package lupos.endpoint.client.formatreader.tsv;
public interface TSVParserTreeConstants
{
  /** Constant <code>JJTRESULT=0</code> */
  public int JJTRESULT = 0;
  /** Constant <code>JJTVARS=1</code> */
  public int JJTVARS = 1;
  /** Constant <code>JJTONERESULT=2</code> */
  public int JJTONERESULT = 2;
  /** Constant <code>JJTVAR=3</code> */
  public int JJTVAR = 3;
  /** Constant <code>JJTVALUE=4</code> */
  public int JJTVALUE = 4;
  /** Constant <code>JJTNIL=5</code> */
  public int JJTNIL = 5;
  /** Constant <code>JJTRDFLITERAL=6</code> */
  public int JJTRDFLITERAL = 6;
  /** Constant <code>JJTDOUBLECIRCUMFLEX=7</code> */
  public int JJTDOUBLECIRCUMFLEX = 7;
  /** Constant <code>JJTLANGTAG=8</code> */
  public int JJTLANGTAG = 8;
  /** Constant <code>JJTVOID=9</code> */
  public int JJTVOID = 9;
  /** Constant <code>JJTINTEGER=10</code> */
  public int JJTINTEGER = 10;
  /** Constant <code>JJTFLOATINGPOINT=11</code> */
  public int JJTFLOATINGPOINT = 11;
  /** Constant <code>JJTBOOLEANLITERAL=12</code> */
  public int JJTBOOLEANLITERAL = 12;
  /** Constant <code>JJTSTRINGLITERAL=13</code> */
  public int JJTSTRINGLITERAL = 13;
  /** Constant <code>JJTQUOTEDURIREF=14</code> */
  public int JJTQUOTEDURIREF = 14;
  /** Constant <code>JJTBLANKNODE=15</code> */
  public int JJTBLANKNODE = 15;
  /** Constant <code>JJTEMPTYNODE=16</code> */
  public int JJTEMPTYNODE = 16;


  /** Constant <code>jjtNodeName="{Result,Vars,OneResult,Var,Value,NIL,RD"{trunked}</code> */
  public String[] jjtNodeName = {
    "Result",
    "Vars",
    "OneResult",
    "Var",
    "Value",
    "NIL",
    "RDFLiteral",
    "DoubleCircumflex",
    "LangTag",
    "void",
    "Integer",
    "FloatingPoint",
    "BooleanLiteral",
    "StringLiteral",
    "QuotedURIRef",
    "BlankNode",
    "EmptyNode",
  };
}
/* JavaCC - OriginalChecksum=8f4d78ad2a3aa3790097fb230008bb97 (do not edit this line) */
